version: 0.1
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: {{ s3.accesskey }}
    secretkey: {{ s3.secretkey }}
    region: {{ s3_region }}
    bucket: {{ s3_bucket }}
    secure: true
    v4auth: true
    chunksize: 5242880
  delete:
    enabled: true
http:
  addr: :5000
  net: tcp
  host: {{ docker_registry_host }}
  secret: {{ docker_registry_secret }}
  relativeurls: false
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: "https://{{ tls_cert_host_acme }}/auth"
    service: "docker.registry"
    issuer: "Acme auth server"
    rootcertbundle: /certs/{{ tls_cert_host_acme }}.crt
